// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RepositoryLayer.Models
{
    public partial class GetCityResult
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int? StateID { get; set; }
        public string StateName { get; set; }
        public int? CountryID { get; set; }
        public string CountryName { get; set; }
    }
}
